spring:
  application:
    name: demo-portal
  profiles:
    active: dev # 默认为开发环境
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.example.demo.entity, com.example.demo.dto, com.example.demo.domain
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  # 指定包别名
  type-aliases-package: com.example.demo.entity, com.example.demo.dto, com.example.demo.domain
  # 加载全局的配置文件
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: is_delete
      logic-not-delete-value: 0
      logic-delete-value: 1

springfox:
  documentation:
    enabled: true

# 禁止actuator监控redis连接
management:
  health:
    redis:
      enabled: false

# 自定义redis
redis:
  database: demo
  key:
    authCode: "ums:authCode" # 登录验证码
    member: "ums:member" # 用户信息
    store: "sms:store" # 商铺信息
    storeCategory: "sms:store:category" # 商铺种类
    couponHistory: "sms:coupon:history" # 优惠券历史记录
    reviewLike: "sms:review:like" # 商铺点评点赞信息
    follow: "ums:follow" # 关注信息
  lock:
    store: "sms:lock:store" # 商铺信息锁
    storeCategory: "sms:lock:store:category" # 商铺种类锁
    couponHistory: "coupon:history" # 商铺优惠券历史锁
    couponStock: "coupon:stock" # 商铺优惠券库存数量
  expire:
    authCode: 120 # 验证码超期时间
    common: 86400 # 24小时
    pierce: 30 # 缓存空对象时间（避免缓存穿透）
    lock: 10 # 互斥锁解锁最长时间
    logical: 10 # 逻辑过期时间

jwt:
  tokenHeader: Authorization # JWT存储的请求头
  tokenHead: 'Bearer ' # JWT负载中的开头
  secret: demo-portal-secret # JWT加解密使用的密钥
  expiration: 604800 # JWT的超期限时间(60*60*24*7)
